current value:  
current value:  
current value: h
[ ]
current value: e
[ ]
current value: l
[ ]
current value: l
[ ]
current value: o
[ ]
current value:  
current value:  
current value: w
[  hello ]
current value: o
[  hello ]
current value: r
[  hello ]
current value: l
[  hello ]
current value: d
[  hello ]
current value:  
current value:  
--- FAIL: TestCase (0.00s)
    repl_test.go:32: The words in the slices do not match
    repl_test.go:32: The words in the slices do not match
panic: runtime error: index out of range [2] with length 2 [recovered]
	panic: runtime error: index out of range [2] with length 2

goroutine 6 [running]:
testing.tRunner.func1.2({0x568d40, 0xc0000161b0})
	/home/linuxbrew/.linuxbrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1()
	/home/linuxbrew/.linuxbrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1737 +0x35e
panic({0x568d40?, 0xc0000161b0?})
	/home/linuxbrew/.linuxbrew/Cellar/go/1.24.3/libexec/src/runtime/panic.go:792 +0x132
command-line-arguments.TestCase(0xc000003880)
	/home/reklai/coding/personal/golang/pokedexcli/repl_test.go:30 +0x215
testing.tRunner(0xc000003880, 0x585300)
	/home/linuxbrew/.linuxbrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1792 +0xf4
created by testing.(*T).Run in goroutine 1
	/home/linuxbrew/.linuxbrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1851 +0x413
FAIL	command-line-arguments	0.004s
FAIL
